// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
      // TODO: Handle this case.
      case TargetPlatform.linux:
      // TODO: Handle this case.
      case TargetPlatform.windows:
        return web;
    // TODO: Handle this case.
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwNudFfXNTCGP7w201i1PhzZkjD6iRdPI',
    appId: '1:1029410372305:android:df74a64f6dd4f7356263f0',
    messagingSenderId: '1029410372305',
    projectId: 'healthapp-a107f',
    storageBucket: 'healthapp-a107f.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    iosBundleId: 'com.quarks.daddyinsurance',
    apiKey: 'AIzaSyBs7Ep-hWlKOVT9NNccTsQoquhFxI-2b1Q',
    appId: '1:462307133199:ios:c44207eaa0b628bdbfe07a',
    messagingSenderId: '462307133199',
    projectId: 'daddy-insurance',
    storageBucket: 'daddy-insurance.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCheJXciBgHdL5e0qWBcvN3i8OhAY_3tLQ",
      authDomain: "daddy-insurance.firebaseapp.com",
      databaseURL: "https://daddy-insurance-default-rtdb.firebaseio.com",
      projectId: "daddy-insurance",
      storageBucket: "daddy-insurance.appspot.com",
      messagingSenderId: "462307133199",
      appId: "1:462307133199:web:a0c390ff9c5cffc5bfe07a",
      measurementId: "G-YCMH02VVEH");
}
